language: java
jdk:
 - oraclejdk9
 - openjdk11
 - openjdk10
 - openjdk8
 - openjdk7
cache:
  directories:
   - $HOME/.m2
before_cache:
 - rm -rf $HOME/.m2/repository/com/restfb/
script:
 - chmod +x sonar.sh
 - ./sonar.sh
